1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

mat1 = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[ 1  4  6]
 [ 7  5 88]
 [ 8  5 77]]  and 

[[12 43 74]
 [ 5  8  3]
 [ 8  9  9]]  is 

[[13 47 80]
 [12 13 91]
 [16 14 86]] 


2.	Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[13,42,64],
        [3,7,4],
        [9,1,2]])
mat2 = np.array([[2,4,7],
        [55,67,8],
        [8,9,1]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[13 42 64]
 [ 3  7  4]
 [ 9  1  2]]  and 

[[ 2  4  7]
 [55 67  8]
 [ 8  9  1]]  is 

[[2848 3442  491]
 [ 423  517   81]
 [  89  121   73]] 


3.	Write a Python Program to Transpose a Matrix?

In [3]:
mat1 = np.array([[13,42,64],
        [3,7,4],
        [9,1,2]])
mat1.transpose()

array([[13,  3,  9],
       [42,  7,  1],
       [64,  4,  2]])

4.	Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
Arr = input("Enter string: ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string: i am bhargav
am
bhargav
i


5.	Write a Python Program to Remove Punctuation From a String?

In [6]:
punctuations = '''!()+-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuations
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }jnf ijr89*(9y 98&Y7^6%&&&&^$$*))$ tUty987$%
jnf ijr899y 98Y76 tUty987
